version: '2'

services:
  user-management:
    image: 'user-management:latest'
    build: .
    container_name: user-management
    depends_on:
      - user-management-db
    ports:
      - "8081:8080"
    env_file:
      - .env-docker

  user-management-db:
    image: 'postgres:13.1-alpine'
    container_name: user-management-db
    ports:
      - "5433:5432"

    env_file:
      - .env-docker